parameters:
  - name: debug
    type: boolean
    default: false

  - name: varGroups
    type: object
    default: {}

  - name: vmImage
    type: string
    default: 'ubuntu-latest'

  - name: installTerraform
    type: boolean
    default: true

  - name: terraformVersion
    type: string
    default: 0.13.4

  - name: installConftest
    type: boolean
    default: true

  - name: conftestVersion
    type: string
    default: 0.21.0

  - name: installTFLint
    type: boolean
    default: true

  - name: tflintVersion
    type: string
    default: 0.20.2

  - name: tflintRulesetAzurermVersion
    type: string
    default: 0.5.0

  - name: workingDirectory
    type: string

  - name: backendKey
    type: string

  - name: prComments
    type: boolean
    default: true

  - name: preInitSteps
    type: stepList
    default: []

  - name: postInitSteps
    type: stepList
    default: []

  - name: planEnvVars
    type: object
    default: {}

  - name: planExtraArgs
    type: string
    default: ""

  - name: prePlanSteps
    type: stepList
    default: []

  - name: postPlanSteps
    type: stepList
    default: []

  - name: environment
    type: string

  - name: validationOnly
    type: boolean
    default: false

  - name: applyEnvVars
    type: object
    default: {}

  - name: applyExtraArgs
    type: string
    default: ""

  - name: preApplySteps
    type: stepList
    default: []

  - name: postApplySteps
    type: stepList
    default: []

stages:
  - stage: Validation
    displayName: "Terraform Static Analysis"
    variables:
      - ${{ each vg in parameters.varGroups }}:
          - group: ${{ vg }}
      - name: System.Debug
        value: ${{ parameters.debug }}
      - name: tfPlanFile
        value: ".terraform/tfplan.out"
      - name: tfJsonFile
        value: ".terraform/tfplan.out.json"
      - name: artifact_name
        value: ${{ parameters.environment }}-plan-$(Build.BuildID)
    jobs:
      - job: Validation
        displayName: "Terraform Static Analysis"
        pool:
          vmImage: ${{ parameters.vmImage }}
        workspace:
          clean: all
        steps:
          - checkout: self
            persistCredentials: true

          - template: install-terraform.yml
            parameters:
              installTerraform: ${{ parameters.installTerraform }}
              terraformVersion: ${{ parameters.terraformVersion }}

          - template: install-conftest.yml
            parameters:
              installConftest: ${{ parameters.installConftest }}
              conftestVersion: ${{ parameters.conftestVersion }}

          - template: install-tflint.yml
            parameters:
              installTFLint: ${{ parameters.installTFLint }}
              tflintVersion: ${{ parameters.tflintVersion }}
              tflintRulesetAzurermVersion: ${{ parameters.tflintRulesetAzurermVersion }}

          - template: terraform-init.yml
            parameters:
              workingDirectory: ${{ parameters.workingDirectory }}
              backendKey: ${{ parameters.backendKey }}
              preInitSteps: ${{ parameters.preInitSteps }}
              postInitSteps: ${{ parameters.postInitSteps }}

          - template: terraform-validate.yml
            parameters:
              workingDirectory: ${{ parameters.workingDirectory }}

          - template: terraform-plan.yml
            parameters:
              workingDirectory: ${{ parameters.workingDirectory }}
              prComments: ${{ parameters.prComments }}
              planEnvVars: ${{ parameters.planEnvVars }}
              planExtraArgs: ${{ parameters.planExtraArgs }}
              tfPlanFile: $(tfPlanFile)
              tfJSONFile: $(tfJsonFile)
              prePlanSteps: ${{ parameters.prePlanSteps }}
              postPlanSteps: ${{ parameters.postPlanSteps }}

          - template: conftest.yml
            parameters:
              workingDirectory: ${{ parameters.workingDirectory }}

          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: "${{ parameters.workingDirectory }}/.terraform"
              artifactName: $(artifact_name)

  - stage: Deploy
    dependsOn: [Validation]
    displayName: "Terraform Deployment"
    variables:
      - ${{ each vg in parameters.varGroups }}:
          - group: ${{ vg }}
      - name: System.Debug
        value: ${{ parameters.debug }}
      - name: tfPlanFile
        value: ".terraform/${{ parameters.tfPlanFile }}"
      - name: tfJsonFile
        value: ".terraform/${{ parameters.tfJSONFile }}"
      - name: artifact_name
        value: ${{ parameters.environment }}-plan-$(Build.BuildID)
    jobs:
      - deployment: Deploy
        displayName: "Terraform Deployment"
        environment: ${{ parameters.environment }}
        pool:
          vmImage: ${{ parameters.vmImage }}
        condition: and(succeeded(), eq('${{ parameters.validationOnly }}', false), in(variables['Build.SourceBranchName'], 'master', 'main'))
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                  persistCredentials: true
                - download: none

                - template: install-terraform.yml
                  parameters:
                    installTerraform: ${{ parameters.installTerraform }}
                    terraformVersion: ${{ parameters.terraformVersion }}

                - task: DownloadPipelineArtifact@2
                  inputs:
                    artifact: $(artifact_name)
                    path: "${{ parameters.workingDirectory }}/.terraform"

                - template: terraform-apply.yml
                  parameters:
                    workingDirectory: ${{ parameters.workingDirectory }}
                    applyEnvVars: ${{ parameters.applyEnvVars }}
                    applyExtraArgs: ${{ parameters.applyExtraArgs }}
                    tfPlanFile: $(tfPlanFile)
                    preApplySteps: ${{ parameters.preApplySteps }}
                    postApplySteps: ${{ parameters.postApplySteps }}

                - template: ../git-set-tag/git-set-tag.yml
                  parameters:
                    workingDirectory: ${{ parameters.workingDirectory }}
