parameters:
  - name: debug
    type: boolean
    default: false

  - name: varGroups
    type: object
    default: {}

  - name: vmImage
    type: string
    default: 'ubuntu-latest'

  - name: installTerraform
    type: boolean
    default: true

  - name: terraformVersion
    type: string
    default: 0.13.4

  - name: installConftest
    type: boolean
    default: true

  - name: conftestVersion
    type: string
    default: 0.21.0

  - name: installTFLint
    type: boolean
    default: true

  - name: tflintVersion
    type: string
    default: 0.20.2

  - name: tflintRulesetAzurermVersion
    type: string
    default: 0.5.0

  - name: preInitSteps
    type: stepList
    default: []

  - name: postInitSteps
    type: stepList
    default: []

  - name: workingDirectory
    type: string

stages:
  - stage: Validation
    displayName: "Terraform Static Analysis"
    variables:
      - ${{ each vg in parameters.varGroups }}:
          - group: ${{ vg }}
      - name: System.Debug
        value: ${{ parameters.debug }}
      - name: installTerraformBinary
        value: ${{ parameters.installTerraform }}
      - name: installConftestBinary
        value: ${{ parameters.installConftest }}
      - name: installTFLintBinary
        value: ${{ parameters.installTFLint }}
    jobs:
      - job: Validation
        displayName: "Terraform Static Analysis"
        pool:
          vmImage: ${{ parameters.vmImage }}
        workspace:
          clean: all
        steps:
          - checkout: self
            persistCredentials: true

          - template: install-terraform.yml
            parameters:
              installTerraform: ${{ parameters.installTerraform }}
              terraformVersion: ${{ parameters.terraformVersion }}

          - template: install-conftest.yml
            parameters:
              installConftest: ${{ parameters.installConftest }}
              conftestVersion: ${{ parameters.conftestVersion }}

          - template: install-tflint.yml
            parameters:
              installTFLint: ${{ parameters.installTFLint }}
              tflintVersion: ${{ parameters.tflintVersion }}
              tflintRulesetAzurermVersion: ${{ parameters.tflintRulesetAzurermVersion }}

          - ${{ each step in parameters.preInitSteps }}:
              - ${{ step }}

          - template: tf-init.yml
            parameters:
              workingDirectory: ${{ parameters.workingDirectory }}

          - ${{ each step in parameters.postInitSteps }}:
              - ${{ step }}

          - template: tf-validate.yml
            parameters:
              workingDirectory: ${{ parameters.workingDirectory }}
